services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: outbox-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: outbox-kafka-broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:14.5
    container_name: outbox-sample-app-postgres
    ports:
      - 5401:5432
    environment:
      POSTGRES_DB: sample-db
      POSTGRES_USER: sample-app-user
      POSTGRES_PASSWORD: password
    command: [ "postgres", "-c", "wal_level=logical" ]

  debezium-connect:
    image: debezium/connect:1.9.5.Final
    container_name: outbox-debezium-connect
    depends_on:
      - kafka
      - postgres
    ports:
      - 8083:8083
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=dbz
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  debezium-connect-init:
    image: debezium-connect-config-init:latest
    build:
      context: debezium-config
      dockerfile: Dockerfile
    depends_on:
      - debezium-connect
    command: sh -c "/usr/local/bin/init.sh && exec myexecutable"

  debezium-ui:
    image: debezium/debezium-ui:1.9.5.Final
    container_name: outbox-debezium-ui
    depends_on:
      - debezium-connect
    ports:
      - 8084:8080
    environment:
      - KAFKA_CONNECT_URIS=http://debezium-connect:8083

  outbox-app:
    image: outbox-app:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - debezium-connect
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sample-db
      - SPRING_DATASOURCE_USERNAME=sample-app-user
      - SPRING_DATASOURCE_PASSWORD=password

  outbox-app-init:
    image: outbox-app-init:latest
    build:
      context: outbox-app-init
      dockerfile: Dockerfile
    depends_on:
      - outbox-app
    command: sh -c "/usr/local/bin/init.sh && exec myexecutable"
